apiVersion: v1
kind: Pod
metadata:
  name: multicontainers
  namespace: expense
spec:
  containers:
  - name: frontend
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "100"]