apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    environment: dev
    component: frontend
spec:
  containers:
  - name: frontend
    image: nginx