apiVersion: v1
kind: Pod
metadata:
  name: frontend-env
  namespace: expense
spec:
  containers:
  - name: frontend-env
    image: nginx
    env:
    - name: course
      value: Devops
    - name: duration
      value: 120 hrs 