apiVersion: v1
kind: Pod
metadata:
  name: frontend-secret
  namespace: expense
spec:
  containers:
  - name: frontend-secret
    image: nginx
    envFrom:
      - secretRef:
           name: secretfile