kind: Service
apiVersion: v1
metadata:
  name: frontend-service-nodeport
  namespace: expense
spec:
  type: NodePort
  selector:
    project: expense
    environment: dev
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001