apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sql
  labels:
    app: guestbook
    tier: database
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: database
  template:
    metadata:
      labels:
        tier: database
    spec:
      containers:
      - name: database
        image: sreenivasuluvanganuru1999/mysql:1.0.0