apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: expense
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sreenivasuluvanganuru1999/nginx
        ports:
        - containerPort: 80
