apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: expense
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: frontend-service-nodeport
  namespace: expense
spec:
  type: NodePort
  selector:
      app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
